export default {
  id: 'ezekiel',
  label: 'Ezekiel',
  colors: {
    bgPage: '#F3F1F1',
    bgSurface: '#F8F6F6',
    bgCode: '#EBEAEA',
    bgMuted: '#EDEBEB',
    borderDefault: '#D4D3D3',
    borderLight: '#DFDEDE',
    textPrimary: '#5a5858',
    textSecondary: '#6e6c6c',
    textMuted: '#908e8e',
    textAccent: '#5a5858',
    colorSyncEdge: '#B8B7B7',
    colorAsyncEdge: '#A8A7A7',
  },
  fonts: {
    serif: "'JetBrains Mono', 'IBM Plex Mono', 'Menlo', monospace",
    sans: "'JetBrains Mono', 'IBM Plex Mono', 'Menlo', monospace",
    mono: "'JetBrains Mono', 'IBM Plex Mono', 'Menlo', monospace",
  },
  mermaid: {
    primaryColor: '#EBEAEA',
    primaryBorderColor: '#D4D3D3',
    primaryTextColor: '#5a5858',
    lineColor: '#B8B7B7',
    secondaryColor: '#E3E2E2',
    tertiaryColor: '#F8F6F6',
  },
  syntax: {
    keyword: '#8a6a5a',
    string: '#7a8a6a',
    number: '#8a7a5a',
    comment: '#a09a94',
    variable: '#6a7a8a',
    title: '#7a6a8a',
    symbol: '#8a7a5a',
    meta: '#7a8080',
    regexp: '#8a6a6a',
    deletion: '#8a6060',
    deletionBg: 'rgba(138, 96, 96, 0.08)',
    addition: '#7a8a6a',
    additionBg: 'rgba(122, 138, 106, 0.08)',
    focusLineBg: 'rgba(0, 0, 0, 0.05)',
  },
  overlayBg: 'rgba(0, 0, 0, 0.45)',
  shadowColor: 'rgba(0, 0, 0, 0.15)',
};
